name: TP1.2

on: 
  pull_request:
    brunches: [master]
    
jobs:
  build:
  
    runs-on: macos-latest
    
    steps:
    - uses: action/checkout@v1
      name: prueba tp 1
    - name: Run a one-line script
      run: echo ¡Prueba TP1 DevOps!
